#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Add home dirs to path
export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:$HOME/.bin:$HOME/.local/bin"

export SSH_KEY_PATH="~/.ssh/id_rsa"

export JAVA_VERSION=1.8

# Rust stuff
#export PATH="$HOME/.cargo/bin:$PATH"
#. "$HOME/.cargo/env"
