# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add home dirs to path
export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/home/amnesia/.bin:/home/amnesia/.cargo/bin"
export XDG_CONFIG_HOME="/usr/home/amnesia/.config"
export XDG_DATA_HOME="/usr/home/amnesia/.local/share"

# TODO: Should this be neovim-remote?
export VISUAL='nvim'
export EDITOR=$VISUAL
export GIT_EDITOR=$VISUAL

export SSH_KEY_PATH="~/.ssh/id_rsa"

export JAVA_VERSION=1.8

# Enable colors and such for git diffs
MORE="-erX" ; export MORE

# Editor specific
alias vi="nvim"
alias vim="nvim"
alias emc="emacs -nw"

# GIT specific
# NB: Other used commands (from plugin?) are:
# gco (checkout), gpc (push), gcm (commit), gcp (cherry-pick),
# gm (merge), gr (rebase), gpp (git pull & push), gp (git push)
# gpt (git push tags)
alias gap="git add --patch"
alias gst="git status -bs"
alias gpl="git pull"

# Others
alias la="ls -ltra"
alias tmux="tmux -2"

# Default C compiler
alias cc="clang"

# XBPS (Voidlinux)
alias xq="xbps-query --regex -Rs"
alias xu="sudo xbps-install -Su"
alias xi="sudo xbps-install -S"

# Python version manager (pyenv)
export PYENV_ROOT="$HOME/.bin/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# LaTeX (TeXLive)
export PATH="$PATH:/opt/texlive/2020/bin/x86_64-linux"

# source the kiex elixir version manager
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
